apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: <REGISTRY_URL>/<REGISTRY_NAMESPACE>/<IMAGE_NAME>:latest
        # Add the URL directly, tell the user where to get the items for the URL
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
